#!/usr/bin/env node
// Docs translations as one JSON file per language, like the web UI's i18n/en.json.
//
//   node tools/docs-i18n.mjs build          regenerate docs/_i18n/en.json and every docs/_<lang>/ page
//   node tools/docs-i18n.mjs check          same as build but writes nothing; exits 1 if anything is out of date
//   node tools/docs-i18n.mjs accept <lang> [key...]
//                                           mark translations as up to date with the current English text
//                                           (all stale keys of <lang> when no key is given)
//
// English pages (docs/*.md, docs/wiki/, docs/progress/) are the source. Their text is split into
// segments (headings, paragraphs, list items, table cells, image captions, button labels) and written to
// docs/_i18n/en.json. A translator copies that file to docs/_i18n/<lang>.json and translates the values.
// The build then rebuilds each English page with the translated text into docs/_<lang>/, so links,
// screenshots and callouts always follow the English structure. Missing keys fall back to English.
//
// docs/_i18n/<lang>.sync.json remembers which English text each translation was made from. When the
// English text changes but the translation doesn't, the key is reported as stale. Editing the translation
// clears it; `accept` clears it when the old translation still fits.
//
// The home page of a translated language also ends with a note (key index:translation-note) that the English
// page doesn't have, e.g. that screenshots show the English UI. It's left out until translated.

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const RootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DocsDir = path.join(RootDir, "docs");
const I18nDir = path.join(DocsDir, "_i18n");
const GeneratedMark = "# Generated by tools/docs-i18n.mjs from docs/_i18n/";
const TranslationNote = { page: "index", key: "translation-note", text: "Screenshots show the English UI." };

// ---------- English pages ----------

function listEnglishPages() {
  const pages = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith("_") || entry.name.startsWith(".") || entry.name === "assets") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".md")) pages.push(path.relative(DocsDir, full).replace(/\\/g, "/"));
    }
  };
  walk(DocsDir);
  // Sidebar order: a page sorts by its own nav_order, a child page by its section's index first.
  const navOrder = (file) => Number(/^nav_order:\s*(\d+)/m.exec(fs.readFileSync(path.join(DocsDir, file), "utf8"))?.[1] ?? 99);
  const sortKey = (file) => {
    const dir = path.posix.dirname(file);
    if (dir === ".") return [navOrder(file), 0];
    return [navOrder(`${dir}/index.md`), file.endsWith("/index.md") ? 0 : navOrder(file)];
  };
  return pages.sort((a, b) => {
    const [x, y] = [sortKey(a), sortKey(b)];
    return x[0] - y[0] || x[1] - y[1];
  });
}

const pageKey = (file) => file.replace(/\.md$/, "");
const hash = (text) => createHash("sha1").update(text).digest("hex").slice(0, 10);

function splitFrontMatter(source) {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(source);
  if (!m) throw new Error("missing front matter");
  const fields = [];
  for (const line of m[1].split("\n")) {
    const kv = /^([A-Za-z_]+):\s*(.*)$/.exec(line);
    if (kv) fields.push([kv[1], kv[2].replace(/^"(.*)"$/, "$1")]);
  }
  return { fields, body: source.slice(m[0].length) };
}

// kramdown's GFM header id: lowercase, drop everything but word chars, spaces and dashes, spaces -> dashes.
const headingId = (text) =>
  text.toLowerCase().replace(/[^\p{L}\p{N}_\- ]/gu, "").replace(/ /g, "-");

const ImageLine = /^\[!\[(.*)\]\(([^)\s]+)\)\]\(([^)\s]+)\)$/;
const ButtonLine = /^\[(.+?)\]\(([^)\s]+)\)(\{:.*\})$/;
const ListItem = /^(\s*)(-|\d+\.)\s+(.*)$/;
const AttrLine = /^\{:.*\}$/;

// Parses one English page into an ordered list of parts. A part is either { raw } (copied as is) or a
// template with translatable segments: { segments: [{ key, text }], render(texts) }.
export function parsePage(source) {
  const { fields, body } = splitFrontMatter(source);
  const title = fields.find(([k]) => k === "title")?.[1] ?? "";
  const blocks = body.replace(/\r\n/g, "\n").trim().split(/\n{2,}/);

  const segments = [];
  const blocksOut = [];
  let section = "intro";
  const counters = {};
  const next = (kind) => {
    const k = `${section}.${kind}`;
    counters[k] = (counters[k] ?? 0) + 1;
    return `${k}${counters[k]}`;
  };
  const add = (key, text) => {
    if (segments.some((s) => s.key === key)) throw new Error(`duplicate key ${key}`);
    segments.push({ key, text });
    return key;
  };

  for (const block of blocks) {
    const lines = block.split("\n");

    if (block === "---" || /^(1\.|-) TOC\n\{:toc\}$/.test(block)) {
      blocksOut.push(() => block);
      continue;
    }

    const heading = /^(#{1,6}) (.+)$/.exec(lines[0]);
    if (heading) {
      const [, hashes, text] = heading;
      const rest = lines.slice(1);
      if (hashes === "#") {
        // The page heading repeats the title; translate it once.
        const key = text === title ? "title" : add(`${section}.heading`, text);
        blocksOut.push((t) => [`${hashes} ${t(key)}`, ...rest].join("\n"));
      } else {
        const id = headingId(text);
        section = id;
        const key = add(`${id}.heading`, text);
        blocksOut.push((t) => [`${hashes} ${t(key)} {#${id}}`, ...rest].join("\n"));
      }
      continue;
    }

    const image = ImageLine.exec(block);
    if (image) {
      const [, alt, src, href] = image;
      const key = add(`${section}.img.${path.basename(src).replace(/\.\w+$/, "")}`, alt);
      blocksOut.push((t, link) => `[![${t(key)}](${link(src)})](${link(href)})`);
      continue;
    }

    if (lines.every((l) => ButtonLine.test(l))) {
      const parts = lines.map((l) => {
        const [, label, href, attr] = ButtonLine.exec(l);
        return { key: add(next("button"), label), href, attr };
      });
      blocksOut.push((t, link) => parts.map((b) => `[${t(b.key)}](${link(b.href)})${b.attr}`).join("\n"));
      continue;
    }

    if (lines[0].startsWith("|")) {
      const tableKey = next("table");
      const rows = lines.map((line, r) => {
        const cells = line.replace(/^\||\|$/g, "").split("|").map((c) => c.trim());
        if (cells.every((c) => /^:?-+:?$/.test(c))) return { raw: line };
        return { keys: cells.map((c, i) => add(`${tableKey}.r${r + 1}c${i + 1}`, c)) };
      });
      blocksOut.push((t) => rows.map((row) => (row.raw ?? `| ${row.keys.map(t).join(" | ")} |`)).join("\n"));
      continue;
    }

    // Leading attribute line (callouts like {: .note }) and trailing one ({: .fs-6 }) stay as they are.
    const lead = AttrLine.test(lines[0]) ? lines.shift() : null;
    const trail = lines.length > 1 && AttrLine.test(lines.at(-1)) ? lines.pop() : null;
    const wrap = (text) => [lead, text, trail].filter((x) => x !== null).join("\n");

    if (ListItem.test(lines[0])) {
      const items = [];
      for (const line of lines) {
        const m = ListItem.exec(line);
        if (m && m[1] === "") items.push({ marker: m[2], text: m[3] });
        else items.at(-1).text += " " + line.trim();
      }
      for (const item of items) item.key = add(next("li"), item.text);
      blocksOut.push((t) => wrap(items.map((i) => `${i.marker} ${t(i.key)}`).join("\n")));
      continue;
    }

    const key = add(next("p"), lines.map((l) => l.trim()).join(" "));
    blocksOut.push((t) => wrap(t(key)));
  }

  return { fields, title, segments: [{ key: "title", text: title }, ...segments], blocksOut };
}

// ---------- output ----------

// Rewrites a link from an English page into a site-absolute relative_url for the translated page.
function makeLinker(file, lang) {
  const dir = path.posix.dirname(file);
  return (href) => {
    if (/^([a-z]+:|#|\{\{)/i.test(href)) return href;
    const [p, anchor] = href.split("#");
    if (p.startsWith("/")) return `{{ '${href}' | relative_url }}`;
    let target = path.posix.normalize(path.posix.join(dir, p));
    if (p.endsWith("/") && !target.endsWith("/")) target += "/";
    const site = target.startsWith("assets/") ? `/${target}` : `/${lang}/${target}`;
    return `{{ '${site}${anchor ? "#" + anchor : ""}' | relative_url }}`;
  };
}

// Inline links inside translated text ([text](url)) get the same treatment.
const relinkText = (text, link) => text.replace(/\]\(([^)\s]+)\)/g, (_, href) => `](${link(href)})`);

function renderPage(file, parsed, lang, translate, titleOf, note) {
  const link = makeLinker(file, lang);
  const t = (key) => relinkText(translate(key), link);
  const front = [`---`, `${GeneratedMark}${lang}.json. Edit that file, not this one.`];
  for (const [k, v] of parsed.fields) {
    if (k === "title") front.push(`title: ${JSON.stringify(translate("title"))}`);
    else if (k === "parent") front.push(`parent: ${JSON.stringify(titleOf(v))}`);
    else front.push(`${k}: ${v}`);
  }
  front.push("---");
  const body = parsed.blocksOut
    .map((render) => render(t, link))
    .map((b) => b.replace(/^\{: \.(note|warning|tip) \}$/gm, `{: .$1-${lang} }`));
  if (note) body.push(`{: .note-${lang} }\n${t(note)}`);
  return `${front.join("\n")}\n\n${body.join("\n\n")}\n`;
}

// ---------- main ----------

const readJson = (file, fallback) => (fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : fallback);
const toJson = (value) => JSON.stringify(value, null, 2) + "\n";

function run(mode, args) {
  const write = mode !== "check";
  const changes = [];
  const writeFile = (file, content) => {
    const old = fs.existsSync(file) ? fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n") : null;
    if (old === content) return;
    changes.push(path.relative(RootDir, file).replace(/\\/g, "/"));
    if (write) {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
    }
  };

  const files = listEnglishPages();
  const pages = files.map((file) => ({ file, key: pageKey(file), parsed: parsePage(fs.readFileSync(path.join(DocsDir, file), "utf8").replace(/\r\n/g, "\n")) }));

  // The translation note isn't part of the English page; add it as an extra segment of the home page.
  const home = pages.find((p) => p.key === TranslationNote.page);
  home.parsed.segments.push({ key: TranslationNote.key, text: TranslationNote.text });

  const en = {};
  for (const page of pages) en[page.key] = Object.fromEntries(page.parsed.segments.map((s) => [s.key, s.text]));
  writeFile(path.join(I18nDir, "en.json"), toJson(en));

  const langs = fs.existsSync(I18nDir)
    ? fs.readdirSync(I18nDir).filter((f) => /^[a-z]{2}\.json$/.test(f) && f !== "en.json").map((f) => f.slice(0, 2))
    : [];
  if (mode === "accept" && !langs.includes(args[0])) throw new Error(`no docs/_i18n/${args[0]}.json`);

  const config = fs.readFileSync(path.join(DocsDir, "_config.yml"), "utf8").replace(/\r\n/g, "\n");
  let failed = false;

  for (const lang of langs) {
    const tr = readJson(path.join(I18nDir, `${lang}.json`), {});
    const syncFile = path.join(I18nDir, `${lang}.sync.json`);
    const sync = readJson(syncFile, {});
    const report = { missing: [], stale: [], unused: [] };
    const newSync = {};

    for (const page of pages) {
      for (const { key, text } of page.parsed.segments) {
        const id = `${page.key}:${key}`;
        const value = tr[page.key]?.[key];
        if (typeof value !== "string" || value === "") { report.missing.push(id); continue; }
        const [enHash, trHash] = (sync[id] ?? "").split(":");
        const accepted = mode === "accept" && (args.length === 1 || args.slice(1).includes(id)) && lang === args[0];
        if (trHash === hash(value) && enHash !== hash(text) && !accepted) {
          // Translation unchanged since the English text moved on.
          report.stale.push(id);
          newSync[id] = sync[id];
        } else {
          newSync[id] = `${hash(text)}:${hash(value)}`;
        }
      }
    }
    for (const [pk, entries] of Object.entries(tr)) {
      for (const key of Object.keys(entries)) if (!(en[pk] && key in en[pk])) report.unused.push(`${pk}:${key}`);
    }
    writeFile(syncFile, toJson(newSync));

    const titles = Object.fromEntries(pages.map((p) => [p.parsed.title, tr[p.key]?.title || p.parsed.title]));
    const generated = new Set();
    for (const page of pages) {
      const out = path.join(DocsDir, `_${lang}`, page.file);
      generated.add(path.resolve(out));
      const translate = (key) => tr[page.key]?.[key] || en[page.key][key];
      const note = page === home && tr[page.key]?.[TranslationNote.key] ? TranslationNote.key : null;
      writeFile(out, renderPage(page.file, page.parsed, lang, translate, (t) => titles[t] ?? t, note));
    }
    // Drop generated pages whose English page is gone.
    const langDir = path.join(DocsDir, `_${lang}`);
    const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]));
    for (const f of fs.existsSync(langDir) ? walk(langDir) : []) {
      if (generated.has(path.resolve(f)) || !fs.readFileSync(f, "utf8").includes(GeneratedMark)) continue;
      changes.push(path.relative(RootDir, f).replace(/\\/g, "/") + " (removed)");
      if (write) fs.rmSync(f);
    }

    const total = pages.reduce((n, p) => n + p.parsed.segments.length, 0);
    console.log(`${lang}: ${total - report.missing.length}/${total} translated, ${report.stale.length} stale, ${report.missing.length} missing, ${report.unused.length} unused`);
    for (const [label, list] of Object.entries(report)) for (const id of list) console.log(`  ${label}: ${id}`);
    for (const need of [`  ${lang}:\n`, `note-${lang}:`, `warning-${lang}:`]) {
      if (!config.includes(need)) { console.log(`  _config.yml has no "${need.trim()}" (collection or callout)`); failed = true; }
    }
  }

  if (changes.length) {
    console.log(`${write ? "Updated" : "Out of date"}:`);
    for (const c of changes) console.log(`  ${c}`);
    if (!write) failed = true;
  } else {
    console.log("Everything is up to date.");
  }
  if (failed) process.exitCode = 1;
}

if (path.resolve(process.argv[1] ?? "") !== fileURLToPath(import.meta.url)) {
  // Imported (e.g. by a one-off migration script); don't run the CLI.
} else {
const [mode = "build", ...args] = process.argv.slice(2);
if (!["build", "check", "accept"].includes(mode) || (mode === "accept" && !args[0])) {
  console.error("usage: node tools/docs-i18n.mjs build | check | accept <lang> [page:key...]");
  process.exit(2);
}
run(mode, args);
}
