title: QuestCodex
description: A quest wiki for your SPT server, mod quests and all.

url: https://viper-9.github.io
baseurl: /QuestCodex

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

color_scheme: questcodex
search_enabled: true
heading_anchors: true

collections:
  kr:
    permalink: "/:collection/:path:output_ext"
    output: true
  ru:
    permalink: "/:collection/:path:output_ext"
    output: true

defaults:
  - scope:
      path: ""
      type: kr
    values:
      layout: default
  - scope:
      path: ""
      type: ru
    values:
      layout: default

just_the_docs:
  collections:
    kr:
      name: 한국어
    ru:
      name: Русский

aux_links:
  GitHub: https://github.com/Viper-9/QuestCodex
  Download: https://github.com/Viper-9/QuestCodex/releases
  Forge: https://sp-mod.com/mod/3054/questcodex
aux_links_new_tab: true

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: yellow
  note-kr:
    title: 참고
    color: blue
  warning-kr:
    title: 주의
    color: yellow
  note-ru:
    title: Примечание
    color: blue
  warning-ru:
    title: Внимание
    color: yellow

footer_content: "Copyright &copy; 2026 Viper-9. All Rights Reserved."
